#   Flake Configuration
#
# Configuration for system environment output. This file should be edited to
# customize the final output based on your system needs.
#
#   Copyright: Banki <contact@xbanki.me>
#              Licensed under the MIT License.
#              See LICENSE for details.

[user]
groups = ["wheel"]       # List of *extra* groups this user belongs in, with
                         # the default group being "users".
name   = "xbanki"        # System user name.
path   = "/home/xbanki"  # Absolute path for the user's home directory.
