#   Flake Configuration
#
# Configuration for system environment output. This file should be edited to
# customize the final output based on your system needs.
#
#   Copyright: Banki <contact@xbanki.me>
#              Licensed under the MIT License.
#              See LICENSE for details.

[user] # Default user configuration, for distributions that don't have one.

# List of extra groups applied to the user. Default groups are:
#
# - users
#
groups = ["wheel"]

# User name. Used as the default user whenever possible (WSL).
name = "xbanki"

# Absolute path for the user's home directory.
path = "/home/xbanki"

# Path where SOPS encryption/ decryption keys live.
sopskey = "/home/xbanki/.config/sops/age/keys.txt"


# File path for encrypted password hash file.
password = "enc/password.yml"

[git] # Git source control management default options.

# Default Git user email.
email      = "contact@xbanki.me"

# Default Git user name.
name       = "xbanki"

# Default Git branch, for newly created local repositories.
mainbranch = "main"

# SSH hosts which get defined in `~/.ssh/config` file.
#
# Each entry in the hosts table maps 1:1 to options found in `ssh_config`,
# with the exception of the `identifier` option, which declares the Host block
# name.
[[ssh.hosts]]
identityFile = "~/.ssh/id_rsa_xbanki"
identifier   = "xbanki.github.com"
hostname     = "github.com"
user         = "git"

# SSH keypair paths which get copied to `~/.ssh/`.
#
# Keys have permissions automatically set based on the `public` flag. The
# applied permissions are as follows:
#
#  - Private: 0600 - Owner read & write
#  - Public:  0644 - Owner read, write, public & group read
#:e 
# Similarly, the `name` value determines the final written filepath inside of
# `~/.ssh`. If the `name` key is set to `id_rsa_foo`, the written key file will
# be `~/.ssh/id_rsa_foo`.
#
# The `key` field determines what field corresponds to the encrypted data found
# within the yaml file. If `key` is omitted, `data` is used as default.
[[ssh.keys]]
path   = "enc/id_rsa_xbanki.yml"
name   = "id_rsa_xbanki"
public = false

[[ssh.keys]]
path   = "enc/id_rsa_xbanki.pub.yml"
name   = "id_rsa_xbanki.pub"
key    = "data"
public = true
