#   Flake Configuration
#
# Configuration for system environment output. This file should be edited to
# customize the final output based on your system needs.
#
#   Copyright: Banki <contact@xbanki.me>
#              Licensed under the MIT License.
#              See LICENSE for details.

[user]
group = "users"        # System user group.
name  = "nixos"        # System user name.
path  = "/home/nixos"  # Absolute path for the user's home directory.
